### ISSUE TITLE
Think about AssetList columns

### ISSUE THREAD

**Issue by Sc3l3t0n** [ProjectCIMS/TuDa.CIMS#47]
We should think about which columns to show in the general overview.

**Comment by anngy12** [comment]
I think Name, Price and Quantity should be enough. That would be a good general overview and you can get more Information by clicking them.

**Comment by Sc3l3t0n** [comment]
Just use AssetItem attributes only

**Comment by Sc3l3t0n** [comment]
Just use AssetItem attributes only
